apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-deploy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/somnathbm/go-echo-app-infra.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: goecho
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true